### ISSUE TITLE
src/test.py returns IndexError: Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by faizantwb** [sparkfish/augraphy#23] opened 2021-07-09 12:12 UTC
The test.py file returns following error:

```
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    crappified = pipeline.augment(img)
  File "autography_tests/env/lib/python3.8/site-packages/Augraphy/AugraphyPipeline.py", line 40, in augment
    self.paper_phase(data)
  File "autography_tests/env/lib/python3.8/site-packages/Augraphy/Augmentations.py", line 29, in __call__
    augmentation(data)
  File "autography_tests/env/lib/python3.8/site-packages/Augraphy/Augmentations.py", line 687, in __call__
    texture = self.get_texture(shape)
  File "autography_tests/env/lib/python3.8/site-packages/Augraphy/Augmentations.py", line 755, in get_texture
    texture = random.choice(self.paper_textures)
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

```

The first iteration of the for loop runs fine.

**Comment by kwcckw** [comment] 2021-07-09 12:22
Yes, actually i'm facing similar issue as well. This issue happened after the major refactoring of the code in the last commit, so @proofconstruction could you look into this ?

**Comment by faizan1041** [comment] 2021-07-09 12:46
@kwcckw this happens randomly, I modified the loop to run only once and it runs fine most of the times but throws some error randomly.

**Comment by proofconstruction** [comment] 2021-07-09 12:53
Yes, I'm working on a PR to fix this and other issues. There is a bigger discussion happening as part of #22 around how to refactor the codebase. This branch is under active development and currently cannot be expected to work as before.

For now, if you need a working version, you can `git checkout 7c6350` or an earlier commit, to go back to the repository state before the reorganization began.

**Comment by kwcckw** [comment] 2021-07-09 12:59
Thanks, then i will continue the development using the prior version until we finalized on the structure of the whole pipeline.

**Comment by proofconstruction** [comment] 2021-07-11 05:45
Which branch and commit of the project are you getting this error on?

**Comment by faizan1041** [comment] 2021-07-11 06:02
commit 2a448e468ebb1a4c380644c67847d531cbc5d095 (HEAD -> dev, origin/dev, origin/HEAD)

**Comment by proofconstruction** [comment] 2021-07-11 06:17
Do you have other changes that are not checked into the dev branch? When I clone the repository and checkout commit `2a448e4`, I don't get this error. I do see another error, which has to do with incorrect naming in the imports. In the first post on this issue, the error message says the most recent error occurred in Augraphy/Augmentations.py at line 755, but Augmentations.py does not exist in commit `2a448e4`.

**Comment by faizan1041** [comment] 2021-07-11 06:20
> Yes, I'm working on a PR to fix this and other issues. There is a bigger discussion happening as part of #22 around how to refactor the codebase. This branch is under active development and currently cannot be expected to work as before.
> 
> For now, if you need a working version, you can `git checkout 7c6350` or an earlier commit, to go back to the repository state before the reorganization began.

I tried on that commit and a few commits before but still the same.

**Comment by proofconstruction** [comment] 2021-07-11 06:27
If you have copied in the old `Augraphy/Augmentations.py`, line 755 in PaperFactory calls `random.choice` on `self.paper_textures`, which is built from files in `texture_path`. In the init method for PaperFactory, one of the parameters is `texture_path="./paper_textures"`, but this is not overridden in the PaperFactory() call in `Augraphy/__init__.py`. It's possible that PaperFactory is trying to call `random.choice` on a list that's still empty, because there is no directory called `./paper_textures` relative to either `__init__.py` or `test.py`. You can try changing that string to a fully-qualified directory location (for example, `texture_path="/home/alex/code/augraphy/paper_textures"` and see if that works.

**Comment by jboarman** [comment] 2021-07-11 18:39
@faizan1041 Can you share a Colab notebook where this issue is occurring?

**Comment by proofconstruction** [comment] 2021-07-12 05:08
I just pushed a new series of commits that undoes a lot of changes and brings the dev branch back to the previous level of stability. You should now be able to clone a new version of the repository and run the test script as before.

Currently this does not fix the problem where PaperFactory will sometimes try to produce a paper image without having read image data in from the paper_textures directory. I will work on this next.

**Comment by proofconstruction** [comment] 2021-07-14 01:12
Interestingly, I can no longer reproduce this error on Ubuntu 21.04.

I changed `cv.waitKey(1000)` to `cv.waitKey(100)` in `src/test.py` so tests would run faster, then in zsh ran the loop `for i in {1..100}; do python test.py; done;` - no errors occurred.

**Comment by proofconstruction** [comment] 2021-07-14 02:27
20 minutes later, I did get the error again.

It turns out that it only happens when you run the `test.py` script from locations other than the top-level project directory. In the PaperFactory class, there is a hardcoded path to `./paper_textures`, which actually doesn't exist in the same directory as the paperfactory module, causing errors when `glob` tries to discover those files. Specifically, `glob.glob(filePath)` can return an empty list. In our case, this was being passed in to `random.choice` [which only takes nonempty lists](https://github.com/python/cpython/blob/3.9/Lib/random.py#L343) and fails otherwise.

**To fix this**, you can do one of the following:
1. always run `python src/test.py` from the top-level `augraphy` directory, or
2. change the PaperFactory constructor in the `paper_phase` declaration of `augraphy/src/augraphy/default/defaultpipeline.py` to reflect the fully-qualified path. For example, I can now execute the test script from anywhere on my system, after changing the constructor call there to `PaperFactory(texture_path="/home/alex/work/sparkfish/code/augraphy/paper_textures")`

**Closed as completed** 2021-07-14 02:28 UTC
Labels: bug

**Comment by kwcckw** [comment] 2021-07-14 08:47
To prevent the similar issue in the future, i think we can add an evaluation to check whether the paper texture is empty and return some warning:

![image](https://user-images.githubusercontent.com/52521979/125592647-8906e02b-4a50-4716-8813-4b6648441e0f.png)
